import type { LiveQuote } from "./api";
import { findIndustryStock, type IndustryConfig } from "./industryConfig";
import type { IndustryAnalysisResult, IndustryPriceScenario, IndustryRankingResponse } from "./types";

type OilGasPage = "overview" | "reversion" | "details" | "scenarios" | "methods";
type OilGasProfile = { structure: string; upstream: number; downstream: number; resource: string; buffer: string; keyVariable: string };
const PROFILES: Record<string, OilGasProfile> = {
  "600938": { structure: "低成本海上上游", upstream: .90, downstream: .10, resource: "油气勘探开发与产量成长", buffer: "低桶油成本与净现金能力", keyVariable: "实现油价、产量、桶油成本和资本开支" },
  "601857": { structure: "上游 + 炼化销售 + 天然气", upstream: .62, downstream: .38, resource: "国内外油气资源与天然气产业链", buffer: "一体化经营和天然气业务", keyVariable: "油气实现价格、炼化利润、资本效率" },
  "600028": { structure: "炼化销售为主的一体化能源", upstream: .38, downstream: .62, resource: "炼化产能、终端网络和化工客户", buffer: "炼化销售对上游油价波动形成缓冲", keyVariable: "炼油价差、化工景气、库存损益和销量" },
};
const FALLBACK: OilGasProfile = { structure: "综合油气", upstream: .65, downstream: .35, resource: "油气资源与一体化网络", buffer: "上下游周期互补", keyVariable: "油价、成本、价差和资本纪律" };
const profileFor = (code: string) => PROFILES[code] ?? FALLBACK;
const money = (value: number | null | undefined) => typeof value === "number" ? `¥${value.toFixed(2)}` : "—";
const pct = (value: number | null | undefined, digits = 1) => typeof value === "number" ? `${(value * 100).toFixed(digits)}%` : "—";
const qualityLabel = { reported: "财报原值", derived: "自动派生", proxy: "行业代理" } as const;
const statusLabel = { strong: "强", stable: "稳健", watch: "关注", risk: "风险" } as const;

function Header({ industry, stockCode, quote, analysis, valuationDate }: { industry: IndustryConfig; stockCode: string; quote: LiveQuote | null; analysis: IndustryAnalysisResult | null; valuationDate: string }) {
  const stock = findIndustryStock(industry, stockCode); const p = profileFor(stockCode); const score = Math.round(analysis?.scores.overall ?? stock.qualityScore * .4 + stock.incomeScore * .28 + stock.defenseScore * .32);
  return <section className="oilgas-hero"><div><span className="eyebrow">INTEGRATED ENERGY CONTROL ROOM · {stock.code}</span><h1><i>◆</i>{stock.name}</h1><p>{p.structure} · {p.resource}</p><footer><span>上游敏感度 {pct(p.upstream)}</span><span>炼化销售缓冲 {pct(p.downstream)}</span><span>{p.buffer}</span></footer></div><div className="oilgas-market"><span>{quote ? "实时价格" : "估值收盘"}</span><b>{money(quote?.price ?? analysis?.current_price)}</b><small>{quote ? `${quote.quote_date} ${quote.quote_time}` : analysis?.market_date ?? valuationDate}</small><em>{analysis ? `PE 五年分位 ${pct(analysis.valuation_percentile)}` : "分析后显示中周期估值"}</em></div><div className="oilgas-score"><span>油气周期质量分</span><b>{score}</b><strong>{score >= 82 ? "低成本核心池" : score >= 72 ? "周期平衡池" : "谨慎观察"}</strong><small>中周期现金优先，拒绝永久高油价</small></div></section>;
}

function Overview({ industry, stockCode, analysis }: { industry: IndustryConfig; stockCode: string; analysis: IndustryAnalysisResult | null }) {
  const stock = findIndustryStock(industry, stockCode); const p = profileFor(stockCode); const metrics = analysis?.panorama?.groups.flatMap((g) => g.metrics) ?? []; const byKey = (key: string) => metrics.find((m) => m.key === key); const strongest = [...metrics].sort((a,b)=>b.score-a.score)[0]; const weakest=[...metrics].sort((a,b)=>a.score-b.score)[0];
  const conclusion = !analysis?.panorama ? "点击开始分析后，由真实财报、行情和分红自动生成。" : weakest?.status === "risk" ? `当前首要约束是${weakest.label}（${weakest.value}），一体化叙事不能覆盖该风险。` : analysis.scores.quality >= 75 && analysis.valuation_percentile <= .55 ? "盈利现金含量、资本纪律和中周期估值通过初筛，可进入油价情景检验。" : "经营尚未触发硬否决，但周期位置或估值安全垫不足。";
  const lenses = [["01","油价与盈利代理",`${byKey("oil_revenue_proxy")?.value??"—"} / ${byKey("oil_profit_proxy")?.value??"—"}`,"收入 / 利润同比，识别油气周期"],["02","炼化运营缓冲",`${byKey("gross_margin")?.value??"—"} / ${byKey("inventory_days")?.value??"—"}`,"综合毛利率 / 库存天数"],["03","现金与资本纪律",`${byKey("cfo_to_np")?.value??"—"} / ${byKey("liability_ratio")?.value??"—"}`,"现金转换 / 资产负债率"],["04","股息与估值",`${byKey("dividend_yield")?.value??"—"} / ${byKey("valuation_percentile")?.value??"—"}`,"实际股息率 / 五年PE分位"]];
  return <><section className="automated-industry-conclusion"><div><span>自动结论</span><b>{conclusion}</b><small>{analysis?.panorama?`财报 ${analysis.panorama.report_date} · 行情 ${analysis.market_date}`:"等待数据"}</small></div><div><span>最强指标</span><b>{strongest?`${strongest.label} ${strongest.value}`:"—"}</b><small>{strongest?`评分 ${strongest.score.toFixed(0)}`:"等待分析"}</small></div><div><span>最弱指标</span><b>{weakest?`${weakest.label} ${weakest.value}`:"—"}</b><small>{weakest?`评分 ${weakest.score.toFixed(0)}`:"等待分析"}</small></div></section><section className="oilgas-chain"><div><span>上游实现价格</span><b>油价 × 产量 - 桶油成本</b><small>形成上游盈利弹性</small></div><i>→</i><div><span>炼化销售缓冲</span><b>裂解价差 × 周转 × 库存损益</b><small>平滑部分油价波动</small></div><i>→</i><div><span>自由现金流</span><b>经营现金 - 必要资本开支</b><small>覆盖储量续航和分红</small></div><i>→</i><div><span>股价重估</span><b>中周期EPS × 倍数 + 股息锚</b><small>不外推峰值利润</small></div></section><section className="oilgas-lenses">{lenses.map(([id,title,val,note])=><article key={id}><span>{id} · {title}</span><h2>{val}</h2><p>{note}</p><footer>{analysis?.panorama?.report_date??"待分析"}</footer></article>)}</section><section className="oilgas-bottom"><article><span className="eyebrow">SELECTED ENERGY ASSET</span><h2>{stock.name}研究定位</h2><dl><div><dt>业务结构</dt><dd>{p.structure}</dd></div><div><dt>资源基础</dt><dd>{p.resource}</dd></div><div><dt>周期缓冲</dt><dd>{p.buffer}</dd></div><div><dt>关键变量</dt><dd>{p.keyVariable}</dd></div></dl></article><article><span className="eyebrow">ANTI-TRAP GATES</span><h2>油气股四道否决闸门</h2><ul><li><b>油价</b><span>把供给冲击的高油价当成永续基准</span></li><li><b>成本</b><span>利润上升但综合毛利率和现金恶化</span></li><li><b>资本</b><span>高油价时期举债扩张高成本项目</span></li><li><b>转型</b><span>储量减值与碳成本未进入压力测试</span></li></ul></article></section></>;
}

function Ranking({ industry, stockCode, ranking, loading, error, onSelectStock }: { industry: IndustryConfig; stockCode: string; ranking: IndustryRankingResponse|null; loading:boolean; error:string; onSelectStock:(code:string)=>void }) {
  const metric=(row:IndustryRankingResponse["results"][number],key:string)=>row.key_metrics.find((m)=>m.key===key)?.value??"—";
  return <section className="oilgas-page"><header className="oilgas-page-head"><div><span className="eyebrow">POINT-IN-TIME OIL & GAS PEERS</span><h1>油气龙头自动筛选</h1><p>同一估值日比较油气景气代理、一体化运营、现金负债、实际股息与PE分位。</p></div><span>{ranking?`${ranking.result_count} 家 · ${ranking.valuation_date}`:"自动计算中"}</span></header>{loading&&!ranking&&<div className="industry-ranking-state"><b>正在计算油气同行排名</b><span>对齐财报、现金流和周期估值…</span></div>}{error&&!ranking&&<div className="industry-ranking-state error"><b>同行排名暂不可用</b><span>{error}</span></div>}{ranking&&<div className="oilgas-ranking"><div className="oilgas-rank-row header"><span>排名 / 公司</span><span>业务结构</span><span>收入 / 利润代理</span><span>现金 / 负债</span><span>股息 / PE分位</span><span>综合分</span><span>操作</span></div>{ranking.results.map((row)=>{const p=profileFor(row.stock_code);return <div className={`oilgas-rank-row ${row.stock_code===stockCode?"active":""}`} key={row.stock_code}><span><b>#{row.rank} {row.stock_name}</b><small>{row.stock_code} · {row.report_date??"财报待取"}</small></span><span><b>{p.structure}</b><small>上游 {pct(p.upstream)} / 下游 {pct(p.downstream)}</small></span><span><b>{metric(row,"oil_revenue_proxy")} / {metric(row,"oil_profit_proxy")}</b><small>财务景气代理</small></span><span><b>{metric(row,"cfo_to_np")} / {metric(row,"liability_ratio")}</b><small>现金转换 / 负债率</small></span><span><b>{metric(row,"dividend_yield")} / {pct(row.valuation_percentile)}</b><small>实际股息 / 五年分位</small></span><span><strong>{row.overall_score.toFixed(1)}</strong><small>{row.risk_flags[0]??"无硬风险"}</small></span><span><button type="button" onClick={()=>onSelectStock(row.stock_code)}>{row.stock_code===stockCode?"当前":"查看"}</button></span></div>})}</div>}</section>;
}

function Panorama({ analysis }: { analysis: IndustryAnalysisResult|null }) {
  const p=analysis?.panorama; return <section className="oilgas-page"><header className="oilgas-page-head"><div><span className="eyebrow">AUTOMATED INTEGRATED ENERGY PANORAMA</span><h1>上游、炼化、资本与估值全景</h1><p>有值指标全部来自后端财报、分红和行情；油价、桶油成本和储量替代率缺少统一源时明确标为代理。</p></div><span>{p?`覆盖 ${(p.coverage_ratio*100).toFixed(0)}% · ${p.report_date}`:"等待开始分析"}</span></header>{!p?<div className="industry-ranking-state"><b>尚未生成油气数据全景</b><span>点击“开始分析”读取最新可用财报和行情。</span></div>:<div className="oilgas-panorama">{p.groups.map((g)=><section key={g.id}><header><h2>{g.title}</h2><span>{g.metrics.length} 项</span></header><div className="oilgas-data-head"><span>指标</span><span>真实值</span><span>状态</span><span>口径与来源</span></div>{g.metrics.map((m)=><div className="oilgas-data-row" key={m.key}><span><b>{m.label}</b><small>{qualityLabel[m.quality]}</small></span><span><b>{m.value}</b><small>评分 {m.score.toFixed(0)}</small></span><span className={m.status}>{statusLabel[m.status]}</span><span><b>{m.interpretation}</b><small>{m.source}</small></span></div>)}</section>)}</div>}<p className="oilgas-note">{analysis?.data_note??"分析后显示数据日期和代理指标边界。"}</p></section>;
}

function ScenarioCard({s}:{s:IndustryPriceScenario}) { return <article className={`price-scenario-card ${s.id}`}><header><span>{s.name}</span><em>置信度 {(s.confidence*100).toFixed(0)}%</em></header><div className="price-range"><small>模型价格区间</small><b>{money(s.price_low)} – {money(s.price_high)}</b><strong>中枢 {money(s.price_mid)}</strong></div><div className={`scenario-return ${s.return_mid>=0?"up":"down"}`}>{pct(s.return_mid)}<small>中枢相对现价</small></div><dl><div><dt>中周期盈利变化</dt><dd>{pct(s.earnings_change)}</dd></div><div><dt>目标 PE</dt><dd>{s.target_pe.toFixed(1)}×</dd></div><div><dt>股息锚</dt><dd>{s.dividend_yield_anchor?pct(s.dividend_yield_anchor):"不使用"}</dd></div></dl><ul>{s.triggers.map((t)=><li key={t}>{t}</li>)}</ul><footer>{s.formula}</footer></article> }
function PriceProjection({ analysis }: { analysis: IndustryAnalysisResult|null }) { const p=analysis?.price_projection; if(!p)return <section className="oilgas-page"><div className="industry-ranking-state"><b>等待油气股价情景计算</b><span>点击“开始分析”，后端将生成四档中周期价格区间。</span></div></section>; return <section className="oilgas-page industry-price-page"><header className="oilgas-page-head"><div><span className="eyebrow">INTEGRATED ENERGY PRICE SCENARIOS</span><h1>油气股价情景推演</h1><p>按上游敏感度和炼化销售缓冲归一化盈利，再叠加资本纪律、估值分位与可持续股息锚。</p></div><span>{p.market_date} · {p.model_name}</span></header><section className="price-projection-summary"><div><span>当前收盘价</span><b>{money(p.current_price)}</b><small>行情日 {p.market_date}</small></div><div><span>基准价值中枢</span><b>{money(p.base_value_mid)}</b><small>{pct(p.base_value_mid/p.current_price-1)} 相对现价</small></div><div><span>防守关注价</span><b>{money(p.defensive_entry_price)}</b><small>基准下沿与悲观上沿取安全值</small></div><div className="conclusion"><span>模型结论</span><b>{p.conclusion}</b><small>财报 {p.report_date}</small></div></section><div className="price-scenario-grid">{p.scenarios.map((s)=><ScenarioCard s={s} key={s.id}/>)}</div><p className="oilgas-note">{p.data_note}</p></section> }

function ModelGuide({ analysis, stockCode }: { analysis:IndustryAnalysisResult|null; stockCode:string }) { const p=analysis?.price_projection; const base=p?.scenarios.find((s)=>s.id==="base"); const metrics=analysis?.panorama?.groups.flatMap((g)=>g.metrics)??[]; const val=(key:string)=>metrics.find((m)=>m.key===key)?.value??"—"; const profile=profileFor(stockCode); const scenarioEps=p&&base?p.implied_eps_ttm*(1+base.earnings_change):null; const dividend=metrics.find((m)=>m.key==="dividend_cash_ttm")?.raw_value; const anchor=dividend&&base?.dividend_yield_anchor?dividend/base.dividend_yield_anchor:null; return <section className="oilgas-page industry-method-guide"><header className="oilgas-page-head"><div><span className="eyebrow">OIL & GAS MODEL GUIDE</span><h1>油气指标与价格模型说明</h1><p>使用当前公司的真实数值解释油价敏感度、炼化缓冲、中周期归一和可持续股息。</p></div><span>{p?`示例数据 · ${p.market_date}`:"等待分析数据"}</span></header><div className="method-guide-grid"><article><b>01</b><h2>从当前价格反推EPS</h2><p>当前低PE可能对应高油价利润，不能直接视为便宜。</p><dl><dt>当前价格</dt><dd>{money(p?.current_price)}</dd><dt>当前PE</dt><dd>{p?`${p.current_pe.toFixed(2)}×`:"—"}</dd><dt>隐含EPS TTM</dt><dd>{p?`¥${p.implied_eps_ttm.toFixed(3)}`:"—"}</dd><dt>五年估值分位</dt><dd>{val("valuation_percentile")}</dd></dl><p className="method-example">EPS TTM = 当前价格 ÷ 当前PE，再进行中周期修正。</p></article><article><b>02</b><h2>上游与下游如何区分</h2><p>不同公司使用不同结构权重，不用同一套油价弹性。</p><dl><dt>上游敏感度</dt><dd>{pct(profile.upstream)}</dd><dt>炼化销售缓冲</dt><dd>{pct(profile.downstream)}</dd><dt>收入景气代理</dt><dd>{val("oil_revenue_proxy")}</dd><dt>利润弹性代理</dt><dd>{val("oil_profit_proxy")}</dd></dl><p className="method-example">中国海油偏上游，中石油较均衡，中石化的炼化销售缓冲最高。</p></article><article><b>03</b><h2>中周期盈利与资本闸门</h2><p>只保留部分当期增速，高负债或高位扩张会压低估值。</p><dl><dt>基准盈利变化</dt><dd>{base?pct(base.earnings_change):"—"}</dd><dt>情景EPS</dt><dd>{scenarioEps?`¥${scenarioEps.toFixed(3)}`:"—"}</dd><dt>现金转换</dt><dd>{val("cfo_to_np")}</dd><dt>资产负债率</dt><dd>{val("liability_ratio")}</dd></dl><p className="method-caution">资本开支必须同时服务于储量续航和股东回报，不能只看产量增长。</p></article><article><b>04</b><h2>分红是压力测试锚</h2><p>特别分红和高油价分红不可永久外推。</p><dl><dt>每股实际分红</dt><dd>{val("dividend_cash_ttm")}</dd><dt>当前股息率</dt><dd>{val("dividend_yield")}</dd><dt>基准目标股息率</dt><dd>{base?.dividend_yield_anchor?pct(base.dividend_yield_anchor):"—"}</dd><dt>股息锚价格</dt><dd>{money(anchor)}</dd></dl><p className="method-example">股息锚 = 实际每股分红 ÷ 压力目标股息率。</p></article><article className="wide"><b>05</b><h2>哪些数据仍需要经营披露复核</h2><dl><dt>实现油价</dt><dd>公司实际销售价格，不等于单一Brent现货报价。</dd><dt>桶油成本</dt><dd>需拆分作业费、折旧、税费和运输，不由毛利率直接替代。</dd><dt>储量替代率</dt><dd>验证当前产量和分红是否消耗未来资源基础。</dd><dt>炼化价差</dt><dd>结合裂解价差、化工价差和库存损益解释下游缓冲。</dd></dl><p className="method-caution">当前结构化接口使用财务结果做代理，价格区间是压力测试，不是未来股价保证。</p></article></div></section> }

export function OilGasWorkspace({industry,page,stockCode,quote,valuationDate,analysis,ranking,rankingLoading,rankingError,onSelectStock}:{industry:IndustryConfig;page:OilGasPage;stockCode:string;quote:LiveQuote|null;valuationDate:string;analysis:IndustryAnalysisResult|null;ranking:IndustryRankingResponse|null;rankingLoading:boolean;rankingError:string;onSelectStock:(code:string)=>void}) { return <div className="oilgas-workspace fade-in">{page==="overview"&&<><Header industry={industry} stockCode={stockCode} quote={quote} analysis={analysis} valuationDate={valuationDate}/><Overview industry={industry} stockCode={stockCode} analysis={analysis}/></>}{page==="reversion"&&<Ranking industry={industry} stockCode={stockCode} ranking={ranking} loading={rankingLoading} error={rankingError} onSelectStock={onSelectStock}/>} {page==="details"&&<Panorama analysis={analysis}/>} {page==="scenarios"&&<PriceProjection analysis={analysis}/>} {page==="methods"&&<ModelGuide analysis={analysis} stockCode={stockCode}/>}</div> }
