import type { LiveQuote } from "./api";
import { findIndustryStock, type IndustryConfig } from "./industryConfig";
import { StockLogo } from "./StockLogo";
import type { IndustryAnalysisResult, IndustryPriceScenario, IndustryRankingResponse } from "./types";
import { industryValuationPercentiles } from "./industryValuation";

type TollRoadPage="overview"|"reversion"|"details"|"scenarios"|"methods";
type RoadProfile={network:string;traffic:string;durationFactor:number;durationRisk:string;cashRole:string;keyVariable:string};
const PROFILES:Record<string,RoadProfile>={
 "600377":{network:"长三角核心高速路网",traffic:"客货流均衡、区域经济密度高",durationFactor:1,durationRisk:"相对较低，仍需逐条路产复核",cashRole:"成熟路产现金流 + 股息",keyVariable:"沪宁路车流、扩张回报与收费期限"},
 "600350":{network:"山东省干线高速网络",traffic:"货运与区域工业敏感",durationFactor:.94,durationRisk:"中等，关注改扩建与关联投资",cashRole:"高股息路网",keyVariable:"货车流量、债务和新增项目回报"},
 "001965":{network:"全国化权益路产组合",traffic:"区域分散、投资收益占比较高",durationFactor:.98,durationRisk:"分散但透明度要求更高",cashRole:"分散路产与资本配置",keyVariable:"权益路产分红、投资收益和项目期限"},
 "600012":{network:"安徽省主干高速",traffic:"区域客货流与制造业相关",durationFactor:.90,durationRisk:"中等偏高，成长依赖新增项目",cashRole:"稳健股息",keyVariable:"核心路产期限、车流与资本开支"},
 "600548":{network:"粤港澳湾区路产",traffic:"区域车流强但业务结构较复杂",durationFactor:.88,durationRisk:"较高，需核对外延业务与债务",cashRole:"湾区路产与综合运营",keyVariable:"收费期限、环保业务、负债和分红"},
};
const FALLBACK:RoadProfile={network:"成熟收费路网",traffic:"客货车流",durationFactor:.92,durationRisk:"需逐项目复核",cashRole:"类债现金流",keyVariable:"车流、费率、期限和再投资"};
const profileFor=(code:string)=>PROFILES[code]??FALLBACK; const money=(v:number|null|undefined)=>typeof v==="number"?`¥${v.toFixed(2)}`:"—"; const pct=(v:number|null|undefined,d=1)=>typeof v==="number"?`${(v*100).toFixed(d)}%`:"—"; const qLabel={reported:"财报原值",derived:"自动派生",proxy:"行业代理"} as const; const sLabel={strong:"强",stable:"稳健",watch:"关注",risk:"风险"} as const;

function Header({industry,stockCode,quote,analysis,valuationDate}:{industry:IndustryConfig;stockCode:string;quote:LiveQuote|null;analysis:IndustryAnalysisResult|null;valuationDate:string}){const stock=findIndustryStock(industry,stockCode),p=profileFor(stockCode),score=Math.round(analysis?.scores.overall??stock.qualityScore*.4+stock.incomeScore*.32+stock.defenseScore*.28);return <section className="road-hero"><div><span className="eyebrow">TOLL ROAD CASH-FLOW CONTROL ROOM · {stock.code}</span><h1><StockLogo stockCode={stock.code} stockName={stock.name} className="stock-logo-hero" />{stock.name}</h1><p>{p.network} · {p.traffic}</p><footer><span>收费权系数 {p.durationFactor.toFixed(2)}</span><span>{p.durationRisk}</span><span>{p.cashRole}</span></footer></div><div className="road-market"><span>{quote?"实时价格":"估值收盘"}</span><b>{money(quote?.price??analysis?.current_price)}</b><small>{quote?`${quote.quote_date} ${quote.quote_time}`:analysis?.market_date??valuationDate}</small><em>{industryValuationPercentiles(analysis)}</em></div><div className="road-score"><span>路产现金流质量分</span><b>{score}</b><strong>{score>=84?"核心类债资产":score>=74?"稳健观察池":"期限风险观察"}</strong><small>现金 40% · 期限 25% · 负债 20% · 估值 15%</small></div></section>}

function Overview({industry,stockCode,analysis}:{industry:IndustryConfig;stockCode:string;analysis:IndustryAnalysisResult|null}){const stock=findIndustryStock(industry,stockCode),p=profileFor(stockCode),ms=analysis?.panorama?.groups.flatMap(g=>g.metrics)??[],by=(k:string)=>ms.find(m=>m.key===k),best=[...ms].sort((a,b)=>b.score-a.score)[0],worst=[...ms].sort((a,b)=>a.score-b.score)[0];const conclusion=!analysis?.panorama?"点击开始分析后，由真实财报、分红和点时行情自动生成。":worst?.status==="risk"?`当前首要约束是${worst.label}（${worst.value}），高股息不能覆盖收费权或债务风险。`:analysis.scores.quality>=75&&analysis.valuation_percentile<=.55?"车流现金代理、债务和有限期限估值通过初筛，可进入收费政策压力测试。":"经营未触发硬否决，但期限或估值安全垫不足。";const lenses=[["01","车流费率代理",`${by("traffic_revenue_proxy")?.value??"—"} / ${by("traffic_profit_proxy")?.value??"—"}`,"收入 / 利润同比，识别车流方向"],["02","路产现金效率",`${by("cfo_to_revenue")?.value??"—"} / ${by("asset_turnover")?.value??"—"}`,"经营现金收入比 / 资产周转"],["03","债务承载",`${by("cfo_to_np")?.value??"—"} / ${by("liability_ratio")?.value??"—"}`,"现金转换 / 资产负债率"],["04","股息与估值",`${by("dividend_yield")?.value??"—"} / ${by("valuation_percentile")?.value??"—"}`,"实际股息率 / 五年PE分位"]];return <><section className="automated-industry-conclusion"><div><span>自动结论</span><b>{conclusion}</b><small>{analysis?.panorama?`财报 ${analysis.panorama.report_date} · 行情 ${analysis.market_date}`:"等待数据"}</small></div><div><span>最强指标</span><b>{best?`${best.label} ${best.value}`:"—"}</b><small>{best?`评分 ${best.score.toFixed(0)}`:"等待分析"}</small></div><div><span>最弱指标</span><b>{worst?`${worst.label} ${worst.value}`:"—"}</b><small>{worst?`评分 ${worst.score.toFixed(0)}`:"等待分析"}</small></div></section><section className="road-chain"><div><span>车流与费率</span><b>客货车流 × 单车收入</b><small>形成通行收入</small></div><i>→</i><div><span>路产现金</span><b>收入 - 养护 - 税费</b><small>成本弹性有限</small></div><i>→</i><div><span>期限与债务</span><b>剩余收费现金 - 净债务</b><small>拒绝永续估值</small></div><i>→</i><div><span>股东回报</span><b>有限期价值 + 可持续股息</b><small>新增项目必须创造价值</small></div></section><section className="road-lenses">{lenses.map(([id,t,v,n])=><article key={id}><span>{id} · {t}</span><h2>{v}</h2><p>{n}</p><footer>{analysis?.panorama?.report_date??"待分析"}</footer></article>)}</section><section className="road-bottom"><article><span className="eyebrow">SELECTED ROAD ASSET</span><h2>{stock.name}研究定位</h2><dl><div><dt>路网结构</dt><dd>{p.network}</dd></div><div><dt>车流特征</dt><dd>{p.traffic}</dd></div><div><dt>期限风险</dt><dd>{p.durationRisk}</dd></div><div><dt>关键变量</dt><dd>{p.keyVariable}</dd></div></dl></article><article><span className="eyebrow">ANTI-TRAP GATES</span><h2>收费公路四道否决闸门</h2><ul><li><b>期限</b><span>把有限收费权按永续现金流估值</span></li><li><b>车流</b><span>并表增长冒充同口径自然增长</span></li><li><b>债务</b><span>剩余期限缩短但净债务不下降</span></li><li><b>扩张</b><span>高股息现金被低回报项目持续消耗</span></li></ul></article></section></>}

function Ranking({stockCode,ranking,loading,error,onSelectStock}:{stockCode:string;ranking:IndustryRankingResponse|null;loading:boolean;error:string;onSelectStock:(c:string)=>void}){const mv=(r:IndustryRankingResponse["results"][number],k:string)=>r.key_metrics.find(m=>m.key===k)?.value??"—";return <section className="road-page"><header className="road-head"><div><span className="eyebrow">POINT-IN-TIME TOLL ROAD PEERS</span><h1>优质路产自动筛选</h1><p>同一估值日比较车流费率代理、现金转换、债务、实际股息与估值分位。</p></div><span>{ranking?`${ranking.result_count} 家 · ${ranking.valuation_date}`:"自动计算中"}</span></header>{loading&&!ranking&&<div className="industry-ranking-state"><b>正在计算公路同行排名</b><span>逐家公司对齐路产现金、债务和估值…</span></div>}{error&&!ranking&&<div className="industry-ranking-state error"><b>同行排名暂不可用</b><span>{error}</span></div>}{ranking&&<div className="road-ranking"><div className="road-row header"><span>排名 / 公司</span><span>路网 / 期限</span><span>收入 / 利润代理</span><span>现金 / 负债</span><span>股息 / PE分位</span><span>综合分</span><span>操作</span></div>{ranking.results.map(r=>{const p=profileFor(r.stock_code);return <div className={`road-row ${r.stock_code===stockCode?"active":""}`} key={r.stock_code}><span><b className="stock-name-with-logo"><StockLogo stockCode={r.stock_code} stockName={r.stock_name} className="stock-logo-ranking" /><span>#{r.rank} {r.stock_name}</span></b><small>{r.stock_code} · {r.report_date??"财报待取"}</small></span><span><b>{p.network}</b><small>期限系数 {p.durationFactor.toFixed(2)}</small></span><span><b>{mv(r,"traffic_revenue_proxy")} / {mv(r,"traffic_profit_proxy")}</b><small>车流费率财务代理</small></span><span><b>{mv(r,"cfo_to_np")} / {mv(r,"liability_ratio")}</b><small>现金转换 / 负债率</small></span><span><b>{mv(r,"dividend_yield")} / {pct(r.valuation_percentile)}</b><small>实际股息 / 五年分位</small></span><span><strong>{r.overall_score.toFixed(1)}</strong><small>{r.risk_flags[0]??"无硬风险"}</small></span><span><button type="button" onClick={()=>onSelectStock(r.stock_code)}>{r.stock_code===stockCode?"当前":"查看"}</button></span></div>})}</div>}</section>}

function Panorama({analysis}:{analysis:IndustryAnalysisResult|null}){const p=analysis?.panorama;return <section className="road-page"><header className="road-head"><div><span className="eyebrow">AUTOMATED TOLL ROAD PANORAMA</span><h1>车流、路产、债务与分红全景</h1><p>真实值来自后端财报、分红与行情；车流、费率和收费期限缺少统一源时明确标为代理或研究系数。</p></div><span>{p?`覆盖 ${(p.coverage_ratio*100).toFixed(0)}% · ${p.report_date}`:"等待开始分析"}</span></header>{!p?<div className="industry-ranking-state"><b>尚未生成公路数据全景</b><span>点击“开始分析”读取最新财报和行情。</span></div>:<div className="road-panorama">{p.groups.map(g=><section key={g.id}><header><h2>{g.title}</h2><span>{g.metrics.length} 项</span></header><div className="road-data-head"><span>指标</span><span>真实值</span><span>状态</span><span>口径与来源</span></div>{g.metrics.map(m=><div className="road-data-row" key={m.key}><span><b>{m.label}</b><small>{qLabel[m.quality]}</small></span><span><b>{m.value}</b><small>评分 {m.score.toFixed(0)}</small></span><span className={m.status}>{sLabel[m.status]}</span><span><b>{m.interpretation}</b><small>{m.source}</small></span></div>)}</section>)}</div>}<p className="road-note">{analysis?.data_note??"分析后显示数据日期和代理边界。"}</p></section>}

function SCard({s}:{s:IndustryPriceScenario}){return <article className={`price-scenario-card ${s.id}`}><header><span>{s.name}</span><em>置信度 {(s.confidence*100).toFixed(0)}%</em></header><div className="price-range"><small>模型价格区间</small><b>{money(s.price_low)} – {money(s.price_high)}</b><strong>中枢 {money(s.price_mid)}</strong></div><div className={`scenario-return ${s.return_mid>=0?"up":"down"}`}>{pct(s.return_mid)}<small>中枢相对现价</small></div><dl><div><dt>盈利变化</dt><dd>{pct(s.earnings_change)}</dd></div><div><dt>目标PE</dt><dd>{s.target_pe.toFixed(1)}×</dd></div><div><dt>股息锚</dt><dd>{s.dividend_yield_anchor?pct(s.dividend_yield_anchor):"不使用"}</dd></div></dl><ul>{s.triggers.map(t=><li key={t}>{t}</li>)}</ul><footer>{s.formula}</footer></article>}
function Projection({analysis}:{analysis:IndustryAnalysisResult|null}){const p=analysis?.price_projection;if(!p)return <section className="road-page"><div className="industry-ranking-state"><b>等待公路股价情景计算</b><span>点击“开始分析”，后端会生成四档有限期限价格区间。</span></div></section>;return <section className="road-page industry-price-page"><header className="road-head"><div><span className="eyebrow">FINITE-CONCESSION PRICE SCENARIOS</span><h1>收费公路股价情景推演</h1><p>后端使用车流费率代理、现金转换、债务、期限研究系数和实际分红计算，不使用永续路产假设。</p></div><span>{p.market_date} · {p.model_name}</span></header><section className="price-projection-summary"><div><span>当前收盘价</span><b>{money(p.current_price)}</b><small>行情日 {p.market_date}</small></div><div><span>基准价值中枢</span><b>{money(p.base_value_mid)}</b><small>{pct(p.base_value_mid/p.current_price-1)} 相对现价</small></div><div><span>防守关注价</span><b>{money(p.defensive_entry_price)}</b><small>期限和车流压力后的安全值</small></div><div className="conclusion"><span>模型结论</span><b>{p.conclusion}</b><small>财报 {p.report_date}</small></div></section><div className="price-scenario-grid">{p.scenarios.map(s=><SCard s={s} key={s.id}/>)}</div><p className="road-note">{p.data_note}</p></section>}

function Guide({analysis,stockCode}:{analysis:IndustryAnalysisResult|null;stockCode:string}){const p=analysis?.price_projection,base=p?.scenarios.find(s=>s.id==="base"),ms=analysis?.panorama?.groups.flatMap(g=>g.metrics)??[],v=(k:string)=>ms.find(m=>m.key===k)?.value??"—",profile=profileFor(stockCode),eps=p&&base?p.implied_eps_ttm*(1+base.earnings_change):null,div=ms.find(m=>m.key==="dividend_cash_ttm")?.raw_value,anchor=div&&base?.dividend_yield_anchor?div/base.dividend_yield_anchor:null;return <section className="road-page industry-method-guide"><header className="road-head"><div><span className="eyebrow">TOLL ROAD MODEL GUIDE</span><h1>公路指标与价格模型说明</h1><p>用当前公司的真实数据解释车流代理、有限收费权、债务和股息锚。</p></div><span>{p?`示例数据 · ${p.market_date}`:"等待分析数据"}</span></header><div className="method-guide-grid"><article><b>01</b><h2>为什么不能使用永续估值</h2><p>收费权到期后现金流会终止、续期或进入补偿安排。</p><dl><dt>当前价格</dt><dd>{money(p?.current_price)}</dd><dt>当前PE</dt><dd>{p?`${p.current_pe.toFixed(2)}×`:"—"}</dd><dt>隐含EPS</dt><dd>{p?`¥${p.implied_eps_ttm.toFixed(3)}`:"—"}</dd><dt>期限研究系数</dt><dd>{profile.durationFactor.toFixed(2)}</dd></dl><p className="method-example">期限系数只做相对约束；准确剩余年限必须按年报逐条路产复核。</p></article><article><b>02</b><h2>车流与费率如何进入模型</h2><p>财报收入是车流、车型、费率、并表范围的合计结果。</p><dl><dt>车流费率收入代理</dt><dd>{v("traffic_revenue_proxy")}</dd><dt>盈利弹性代理</dt><dd>{v("traffic_profit_proxy")}</dd><dt>基准盈利变化</dt><dd>{base?pct(base.earnings_change):"—"}</dd><dt>情景EPS</dt><dd>{eps?`¥${eps.toFixed(3)}`:"—"}</dd></dl><p className="method-caution">必须排除新并表路产，才能判断同口径自然车流。</p></article><article><b>03</b><h2>现金与债务决定期限价值</h2><p>期限越短，越需要用现金快速偿债，而不是继续扩张。</p><dl><dt>经营现金/净利润</dt><dd>{v("cfo_to_np")}</dd><dt>资产负债率</dt><dd>{v("liability_ratio")}</dd><dt>利息保障</dt><dd>{v("interest_cover")}</dd><dt>资产增速</dt><dd>{v("asset_growth")}</dd></dl><p className="method-example">高负债或成熟期快速扩张会自动压低目标PE。</p></article><article><b>04</b><h2>股息是核心估值锚</h2><p>只有由路产经营现金覆盖的分红才可持续。</p><dl><dt>每股实际分红</dt><dd>{v("dividend_cash_ttm")}</dd><dt>当前股息率</dt><dd>{v("dividend_yield")}</dd><dt>基准目标股息率</dt><dd>{base?.dividend_yield_anchor?pct(base.dividend_yield_anchor):"—"}</dd><dt>股息锚价格</dt><dd>{money(anchor)}</dd></dl><p className="method-example">公路模型的股息锚权重高于消费，但仍接受期限与政策折价。</p></article><article className="wide"><b>05</b><h2>需要从年报和经营公告补齐什么</h2><dl><dt>剩余收费年限</dt><dd>逐条路产的到期日、改扩建补偿和续期机制。</dd><dt>同口径车流</dt><dd>客车、货车流量及单车收入，剔除新并表和分流。</dd><dt>维护资本开支</dt><dd>维持道路服务水平所必需的支出，不能全部当成长投资。</dd><dt>新增项目IRR</dt><dd>必须高于资金成本，避免成熟现金牛被低回报扩张消耗。</dd></dl><p className="method-caution">价格区间是有限期限压力测试，不是未来股价保证。</p></article></div></section>}

export function TollRoadWorkspace({industry,page,stockCode,quote,valuationDate,analysis,ranking,rankingLoading,rankingError,onSelectStock}:{industry:IndustryConfig;page:TollRoadPage;stockCode:string;quote:LiveQuote|null;valuationDate:string;analysis:IndustryAnalysisResult|null;ranking:IndustryRankingResponse|null;rankingLoading:boolean;rankingError:string;onSelectStock:(c:string)=>void}){return <div className="road-workspace fade-in">{page==="overview"&&<><Header industry={industry} stockCode={stockCode} quote={quote} analysis={analysis} valuationDate={valuationDate}/><Overview industry={industry} stockCode={stockCode} analysis={analysis}/></>}{page==="reversion"&&<Ranking stockCode={stockCode} ranking={ranking} loading={rankingLoading} error={rankingError} onSelectStock={onSelectStock}/>} {page==="details"&&<Panorama analysis={analysis}/>} {page==="scenarios"&&<Projection analysis={analysis}/>} {page==="methods"&&<Guide analysis={analysis} stockCode={stockCode}/>}</div>}
